{
    "name": "School Management",
    "summary": "Manage School catalog and Student Details",
    "author": "Tulsi Goswami",
    "license": "AGPL-3",
    "version": "15.0.1.0.0",
    "category": "Services/School",
    "depends": ["base", "mail", "contacts"],
    "data": [
        "data/ir_sequence_data.xml",
        "data/school_demo.xml",
        "data/student_demo.xml",
        "data/teacher_demo.xml",
        "data/department_demo.xml",
        "security/ir.model.access.csv",
        "wizard/checkout_mass_message_wizard_view.xml",
        "views/school_details_view.xml",
        "views/department_details_view.xml",
        "views/student_details_view.xml",
        "views/teacher_details_view.xml",
        "views/student_wizard_view.xml",
        "views/school_menu.xml",
    ],
    "application": True,
    "installable": True,
}
