from . import faculty_schedual
from . import time_table
from . import student_detail
from . import result
from . import res_config_settings
from . import academic_year
from . import class_division
from . import school_class
from . import school_division
