from . import school_addmission_stages
from . import school_checkout
from . import teacher_details
from . import student_register
from . import school_detail
from . import general_detail
from . import medical_detail
from . import contact_detail
from . import remark_detail
from . import academic_detail
